language: go

go:
 - 1.4.2

before_install:
 - sudo pip install codecov

install:
 - go get golang.org/x/tools/cmd/cover
 - go get github.com/smartystreets/goconvey
 - go get github.com/smartystreets/assertions

script:
 - go test -v -coverprofile=coverage.txt -covermode=count

after_success:
 - codecov
